export type FlowProperty = {
  pkid: number;
  id: string;
  projectId: number;
  dataName: string;
  lastChange: Date;
  description: string;
  flowPropertyType: string;
  unitGroupPkid: number;
  unitGroupId: string;
  unitGroupName: string;
  referenceUnit: string;
  categoryId: string;
  categoryPath: string;
  categoryName: string;
  version: string;
  release: string;
  tags: string;
  library: string;
};
