export type Flow = {
  pkid: number;
  id: string;
  projectId: number;
  dataName: string;
  lastChange: Date;
  description: string;
  synonyms: string;
  formula: string;
  flowType: string;
  cas: string;
  categoryId: string;
  categoryPath: string;
  categoryName: string;
  flowPropertyCount: number;
  locationId: string;
  locationName: string;
  version: string;
  release: string;
  tags: string;
  library: string;
};
