export type Process = {
  pkid: number;
  id: string;
  projectId: number;
  dataName: string;
  lastChange: Date;
  description: string;
  processType: string;
  database: string;
  release: string;
  version: string;
  categoryId: string;
  categoryPath: string;
  categoryName: string;
  locationId: string;
  locationName: string;
  defaultAllocationMethod: string;
  dqEntry: string;
  processDocumentationTimeDescription: string;
  processDocumentationTechnologyDescription: string;
  processDocumentationCompletenessDescription: string;
  processDocumentationDataSelectionDescription: string;
  processDocumentationInventoryMethodDescription: string;
  processDocumentationCopyright: boolean;
  processDocumentationCreationDate: Date;
  processDocumentationProjectDescription: string;
  processDocumentationGeographyDescription: string;
  allocationFactors: string;
  processDocumentationReviewDetails: string;
  processDocumentationDataTreatmentDescription: string;
  processDocumentationSamplingDescription: string;
  processDocumentationSources: string;
  processDocumentationValidFrom: Date;
  processDocumentationValidUntil: Date;
  processDocumentationDataDocumentorId: string;
  processDocumentationDataGeneratorId: string;
  processDocumentationModelingConstantsDescription: string;
  processDocumentationIntendedApplication: string;
  processDocumentationRestrictionsDescription: string;
  processDocumentationDataSetOwnerId: string;
  processDocumentationDataCollectionDescription: string;
  processDocumentationReviewerId: string;
  processDocumentationPublicationId: string;
  exchangeDqSystemId: string;
};

export type ParameterJson = {
  id: string;
  projectId: number;
  processPkid: number;
  processId: string;
  name: string;
  formula: string;
  value: number;
  uncertaintyGeomMean: number;
  uncertaintyGeomSd: number;
  version: string;
  description: string;
};

export type ExchangeJson = {
  projectId: number;
  processPkid: number;
  processId: string;
  internalId: number;
  input: boolean;
  amount: number;
  amountFormula: string;
  description: string;
  avoidedProduct: boolean;
  quantitativeReference: boolean;
  flowPkid: number;
  flowId: string;
  flowName: string;
};
